### ISSUE TITLE
Even if I'm logged in as the owner I can't edit or create anything

### ISSUE THREAD

**Issue by capotej** [twilio/stashboard#2]
Just deployed it and despite logging in as the appspot owner account, I can't add any services or events. Always returns "Could not create service. Make sure Name and Description are valid".

**Comment by kyleconroy** [comment]
Hmm. Is this just a regular appspot account or is it through Google Apps?

**Comment by capotej** [comment]
It's a plain appspot account.

**Comment by kyleconroy** [comment]
Any chance you could send me the logs from your app? That would be a huge help. Also, can you create Statuses?

**Comment by capotej** [comment]
Actually, just went to check again and it works! Something about the Indexes not being able to serve yet (this is my first time on appengine). Thanks!

**Comment by kyleconroy** [comment]
No problem, glad to here that it's all working
