### ISSUE TITLE
Wrong content-type value in response headers

### ISSUE THREAD

**Issue by caseysoftware** [twilio/stashboard#20]
The response type of the REST responses of the API calls to Twilio Status http://status.twilio.com/api/v1/services is returned incorrectly as "text/html; charset=utf-8" where as it should be "application/json" as it is a JSON response. 

Source:  http://getsatisfaction.com/twilio/topics/twilio_services_status_rest_api_wrong_content_type_value_in_response_headers

**Comment by kyleconroy** [comment]
Fix committed to develop.
