### ISSUE TITLE
code sample and doc fix

### ISSUE THREAD

**Issue by shermanw** [twilio/stashboard#24]
- change application-id to application: in the "Deploy to AppSpot" docs
- in the python example code, change:
  severity": 10000,
  to:
  "level": "WARNING",
  ...or ERROR, etc.
- Update API docs to reflect that INFO is no longer available

{
    "levels": [
        "INFO", 
        "NORMAL", 
        "WARNING", 
        "ERROR", 
        "CRITICAL",]
}

**Comment by kyleconroy** [comment]
@shermanw Thanks, these have been fixed
