### ISSUE TITLE
Images on Create/Edit Status

### ISSUE THREAD

**Issue by deleto0512** [twilio/stashboard#29]
When i create a new status, i do not have any options to choose an image. It has the title of Images, but no option box or selection.

**Comment by maxcountryman** [comment]
+1 I can't seem to figure out what's intended here...

**Comment by maxcountryman** [comment]
Although it does not appear to be listed anywhere on their actual project site, you need to run http://localhost:8080/admin/setup before adding new statuses see this as well: http://readthedocs.org/docs/stashboard/en/latest/quickstart.html

**Comment by amferraz** [comment]
I ran into a simillar issue (not showing any item for image), and going to http://{my-app}.appspot.com/admin/setup solved it.

**Comment by apanzerj** [comment]
Sweet tap-dancing django code! This solved my problem.

**Comment by kyleconroy** [comment]
Since many people are missing the setup page, I'm going to change it so that the setup code is run automatically.

**Comment by kyleconroy** [comment]
@apanzerj are you talking about your rss problem?

**Comment by kyleconroy** [comment]
Now when you go to the admin portal, it will redirect you to http://localhost:8080/admin/setup unless you've already loaded the defaults. You can skip the process if you've already run the setup.
