### ISSUE TITLE
Event links on first page have an offset of +1 day

### ISSUE THREAD

**Issue by dvbportal** [twilio/stashboard#3]
The icons in the column "7/24/2010" link to http://<url>/services/<service>/2010/7/25 and so on.

(using master branch)

**Comment by kyleconroy** [comment]
Thanks for the heads up. I am busy this weekend, but a fix will be in early next week.

**Comment by dvbportal** [comment]
Thanks for looking at it. The stashboard is live at the http://status.jgate.de. Also a big thank you for making this great piece of software available as open source.

**Comment by wickett** [comment]
I am experiencing this same problem.  Is there a fix for this?

**Comment by kyleconroy** [comment]
wickett, I just finished my summer internship, so I am going to be working on fixing this bug ASAP

**Comment by wickett** [comment]
Line 363 in common.js needs to be changed to +1 instead of +2.  That fixes it

**Comment by wickett** [comment]
derferman, thanks, I think if you apply the change I did, then that gets it fixed.  Oh, and it is line 362, not 363.  BTW, I am having some trouble testing locally.   Is there a way to download data from appengine to test locally?  I am new to appengine, so I havent figured this out yet.

**Comment by kyleconroy** [comment]
wickett, I just pushed version 1.1.5 which includes a fix for this bug. As for downloaded data to test locally, you can run Stashboard using the [App Engine SDK](http://code.google.com/appengine/downloads.html).

**Comment by dvbportal** [comment]
Great, thanks!
