### ISSUE TITLE
history Backup

### ISSUE THREAD

**Issue by chebrian** [twilio/stashboard#31]
Hi, 

I have missed the history of status details in my stashboard. Is there anyway to get the details again . I have run the stashboard locally.

**Comment by sijis** [comment]
You can do this:

http://localhost:8080/services/service-name/date

Specific Date
http://localhost:8080/services/test1/2012/09/7

Specific Month (should work)
http://localhost:8080/services/test1/2012/08

**Comment by chebrian** [comment]
Thanks sijis. I ll check and update
