### ISSUE TITLE
RSS Feeds not working?

### ISSUE THREAD

**Issue by apanzerj** [twilio/stashboard#38]
Not sure if anyone has seen this yet but when you take the RSS feed and ad it to google reader it says there's not feed there. Am I missing something?

**Comment by vmdx** [comment]
It seems to work for me on [Twilio Status](http://status.twilio.com) when I add URLs like these to my Google Reader:
- http://status.twilio.com/rss?services=account-portal
- http://status.twilio.com/rss

EDIT: I'm not sure what happens if the feed is empty, however...

**Comment by kyleconroy** [comment]
@apanzerj Do you have link to the feed causing the problem?

**Comment by kyleconroy** [comment]
@vmdx If the feed is empty, we still return a valid RSS document, just with no entries in it.

**Comment by apanzerj** [comment]
i think my instance just needs more data. I'll close this and try again
