### ISSUE TITLE
Default status of a service for a day

### ISSUE THREAD

**Issue by ducky427** [twilio/stashboard#4]
When looking at the main landing page, for any given service, the web page shows that the service is at the level NORMAL if no information for that particular date is given. Sometimes this can be too optimistic. 

It would be great if we can set the default level for a service.

This only effects the web GUI.

cheers

**Comment by kyleconroy** [comment]
Ducky,

Setting a default status for a service would be a great feature. Currently the default status is the first status with a NORMAL level. Currently the API doesn't support the concept of marking statuses as default, so the object model would have to be modified to make it work.
