### ISSUE TITLE
OAuth Credentials

### ISSUE THREAD

**Issue by jonrohan** [twilio/stashboard#6]
Having trouble accessing my /documentation/credentials page, it says I must be admin, and I'm logged into google app engine as the admin but still cannot access it. This seems super trivial, so any help would be greatly appreciated!

Thanks!

Jon

**Comment by kyleconroy** [comment]
Jon, sorry to hear about the problem. What type of authentication are you using (Google or Google Apps)? Also, are you using a custom domain?

**Comment by jonrohan** [comment]
Using my google account to login to appspot.com, then I can modify and edit my apps. After login I navigate to my site/documentation/credentials and it says that I need to be admin. 

I guess I'm just confused on how to access the credentials generating part of the webapp. What account do I need to be logged in with? Google?

**Comment by jonrohan** [comment]
Just to update, what confused me. In my haste I removed some ui in the styling of the board, and had no admin links. So egg on me :) Thanks for making an awesome open source app.

**Comment by kyleconroy** [comment]
Jon, glad to hear that everything is working. I am planning on splitting up the admin and display sections on Stashboard so that it's easier to make changes to the user-facing pages.

**Comment by usersjuzi** [comment]
I can to open API Credentials ,but consumers are anonymous and post request to stashboard responsed 403 code.
