### ISSUE TITLE
admin/ section is unprotected

### ISSUE THREAD

**Issue by anarcat** [twilio/stashboard#66]
I have tried doing a local deployment (#64) and it seems that there is no authentication on the `admin/` section.

Now I understand the recommended way of using this software is on Google's servers, but I would like to avoid that for various economic and political reasons.

What is the recommended way of protecting the "write" interface to the software? Is it limited to the `/admin` directory? In that case it may be possible to simply use Apache or another webserver to setup a proxy with authentication...

Other ideas?

**Comment by anarcat** [comment]
Some more information about authentication and GAE that I could gleam:

https://developers.google.com/appengine/articles/openid
https://developers.google.com/appengine/docs/python/users/#Python_Authentication_options

Summary: it's pretty hard to do this with the local dev server - this thing really is designed to be deployed in google's silos...

**Comment by kyleconroy** [comment]
@anarcat as you've discovered, Stashboard is meant to be deployed on App Engine (and app engine alone)

**Comment by anarcat** [comment]
I quickly understood that indeed, and it's a very unfortunate design flaw, in my opinion.

However, even if the primary target is appengine, why not make it _possible_ to deploy it elsewhere by plugging those holes?

**Comment by anarcat** [comment]
What about the idea of using nginx or apache as a proxy with access controls?

**Comment by kyleconroy** [comment]
While using nginx or apache would work, the appengine sdk is not meant to serve production traffic.

**Comment by anarcat** [comment]
yay silos.
